### ISSUE TITLE
You should use windows!

### ISSUE THREAD

**Issue by andres-amezquita01** [Nojipiz/dotfiles_nixos#1]

**Comment by andres-amezquita01** [comment]
@Nojipiz

**Comment by Nojipiz** [comment]
@andres-amezquita01  Are u dumb?

**Comment by Nojipiz** [comment]
Actually ... there is a WSL configuration embedded in this flake as well, it shares most of the modules of my Linux setup and runs out of the box with the command in the readme file.

**Comment by Nojipiz** [comment]
Talking about that @andres-amezquita01 could you help me with the darwin implementation of the config? I'd be glad to receive a pull request with that :D
